spring:
  application:
    name: boot-oss

#七牛云配置
qiniu:
  kodo:
    accessKey:
    secretKey:
    # 七牛空间名
    bucket: boot-oss
    # 外链访问CDN域名
    path:
aliyun:
  oss:
    accessKeyId:
    accessKeySecret:
    bucketName: springboot-component
    endpoint: oss-cn-shenzhen.aliyuncs.com
    domain: ${aliyun.oss.bucketName}.${aliyun.oss.endpoint}

