server:
  port: 8080

spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: ENC(hhSOllGOQ9sYBssjrYmyIKxdEJQ7rx5DAtM1/78yiZo=)
    password: ENC(1lkmIGVenzpxFs/i867yO8kTUZ8GTbKyAa7espWABko=)
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

# 加密参数
jasypt:
  encryptor:
    password: springboot-mail
