# SpringBoot 所有的配置类, 都有一个自动配置类 RedisAutoConfiguration
# 自动配置类都会绑定一个 properties 配置文件 RedisProperties
spring:
  redis:
    host: r-2jd987f23671ec34.redis.rds.aliyuncs.com
    password: FL75P10Ple
    port: 6379
