# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema.sql # 每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    data: classpath:db/data.sql # 每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    url: jdbc:h2:mem:mybatisplus # 配置h2数据库的连接地址
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: io.zsy.mybatis.plus.entity
  global-config:
    banner: true # 是否显示 mybatis-plus banner
    db-config:
      id-type: assign_id # 全局设置主键策略
      table-underline: true # 驼峰下划线转换
      #capital-mode: true  # 是否开启大写命名，默认不开启
      # 逻辑删除配置
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
